version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - chat-data:/data/db/
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=chat
      - MONGO_INITDB_ROOT_USERNAME=chat
      - MONGO_INITDB_ROOT_PASSWORD=chatsecret
    networks:
      - chat

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - 8888:8888
    environment:
      - MONGO_HOST=mongodb
    networks:
      - chat

networks:
  chat:

volumes:
  chat-data:
