version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - chat-data:/data/db/
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=chat
      - MONGO_INITDB_ROOT_USERNAME=chat
      - MONGO_INITDB_ROOT_PASSWORD=chatsecret
    networks:
      - chat

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_ui
    ports:
      - 8090:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=chat
      - ME_CONFIG_BASICAUTH_PASSWORD=chatsecret
      - ME_CONFIG_MONGODB_ADMINUSERNAME=chat
      - ME_CONFIG_MONGODB_ADMINPASSWORD=chatsecret
      - ME_CONFIG_MONGODB_URL=mongodb://chat:chatsecret@mongodb:27017/
    networks:
      - chat

networks:
  chat:

volumes:
  chat-data:
