version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - chat-data:/data/db/
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js
    environment:
      - MONGO_INITDB_DATABASE=chat
      - MONGO_INITDB_ROOT_USERNAME=chat
      - MONGO_INITDB_ROOT_PASSWORD=chatsecret
    networks:
      - chat

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      - MONGO_HOST=mongodb
    networks:
      - chat
    depends_on:
      - mongodb

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8888:80
    networks:
      - chat

networks:
  chat:

volumes:
  chat-data:
