FROM node:latest as build
WORKDIR /app
COPY /frontend/package.json ./
COPY /frontend/package-lock.json ./
RUN npm install
COPY frontend ./
RUN npm run build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]